routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// php artisan route:list
Auth::routes();

// https://laravel.com/docs/5.6/controllers#resource-controllers
Route::resource('webpages', 'WebpageController');

Route::get('/', 'WebpageController@index')->name('home');

Route::resource('user.userWebpage', 'UserWebpageController')->only([
    'store', 'destroy'
]);

Route::resource('collection.user', 'CollectionUserController')->only([
    'store', 'update', 'destroy'
]);
Route::post('collection/{collection}/user/bulk-delete', 'CollectionUserController@bulkDestroy');
Route::post('collection/{collection}/user/bulk-update', 'CollectionUserController@bulkUpdate');

Route::resource('collection', 'CollectionController');

Route::resource('collections.userWebpage', 'CollectionUserWebpageController')->only([
    'store', 'destroy'
]);

resources/views/partials/create-form.blade.php
<div>
    @if ( $errors->has('title') || $errors->has('description') )
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
    <form action="{{ route('collection.store') }}" method="POST">
        @csrf
        <div class="form-group">
            <label for="collection-title-input">Title</label>
            <input type="text" name="title" id="collection-title-input" class="form-control">
        </div>
        <div class="form-group">
            <label for="collection-desc-input">Description</label>
            <input type="text" name="description" id="collection-desc-input" class="form-control">
        </div>
        <button class="btn btn-primary">Create</button>
    </form>
</div>