routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// php artisan route:list
Auth::routes();

// https://laravel.com/docs/5.6/controllers#resource-controllers
Route::resource('webpages', 'WebpageController');

Route::get('/', 'WebpageController@index')->name('home');

Route::resource('user.userWebpage', 'UserWebpageController')->only([
    'store', 'destroy'
]);

Route::resource('collection.user', 'CollectionUserController')->only([
    'store', 'update', 'destroy'
]);
Route::post('collection/{collection}/user/bulk-delete', 'CollectionUserController@bulkDestroy');
Route::post('collection/{collection}/user/bulk-update', 'CollectionUserController@bulkUpdate');

Route::resource('collection', 'CollectionController');

Route::resource('collections.userWebpage', 'CollectionUserWebpageController')->only([
    'store', 'destroy'
]);

app/Collection.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Collection extends Model
{
    protected $fillable = ['title', 'description', 'user_id', 'is_public'];

    protected $with = ['user'];

    public function user(){
        return $this->belongsTo('App\User');
    }

    public function userWebpages(){
        return $this->belongsToMany('App\UserWebpage', 'collection_user_webpage', 'collection_id', 'user_webpage_id')->using('App\CollectionUserWebpage')->withTimestamps();
    }

    public function path(){
        return "/collection/{$this->id}";
    }

    public function setIsPublicAttribute($value)
    {
        if( $value === true ){
            $this->attributes['is_public'] = 1;
        } else if( $value === false ){
            $this->attributes['is_public'] = 0;
        }
    }

    public function makePublic(){
        $this->is_public = true;
        $this->save();
    }

    public function makePrivate(){
        $this->is_public = false;
        $this->save();
    }

    public function getIsPublicAttribute($value){
        return boolval( $value );
    }
}

app/Http/Controllers/CollectionController.php
<?php

namespace App\Http\Controllers;

use App\Collection;
use App\UserWebpage;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use App\Services\CollectionPermissionsManager;
use Validator;
use Exception;
use ReflectionClass;

class CollectionController extends Controller
{
    public function __construct(){
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $user = Auth::user();
        $collections = $user->collections;

        return $collections;
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->authorize('create', Collection::class);

        // Validate request
        // Create new collection
        $request->validate([
            'title' => 'required|string',
            'description' => 'nullable|string'
        ]);

        $collection = Collection::create([
            'user_id' => auth()->id(),
            'title' => request('title'),
            'description' => request('description')
        ]);

        return redirect( $collection->path() );
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Collection  $collection
     * @return \Illuminate\Http\Response
     */
    public function show(Request $request, Collection $collection)
    {
        $this->authorize('view', $collection);

        // Get all of user's webpages in this collection
        $collectionUserWebpages = $collection->userWebpages()->get();

        // For current user, get all of user's webpages not in this collection.
        $userWebpageIDsInCollection = $collectionUserWebpages->pluck('id');
        $userWebpagesNotInCollection = UserWebpage::fromUser( Auth::id() )->whereNotIn('id', $userWebpageIDsInCollection)->get();


        $collectionUsers = app('App\Services\CollectionPermissionsManager')->retrieveCollectionUsers( $collection->id );

        $availableRoles = \App\Role::all();

        return view('layouts.collections.show', compact('collection', 'collectionUserWebpages', 'userWebpagesNotInCollection', 'availableRoles', 'collectionUsers'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Collection  $collection
     * @return \Illuminate\Http\Response
     */
    public function edit(Collection $collection)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Collection  $collection
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Collection $collection)
    {
        // @TODO: prevent duplicate roles for a user on 1 collection
        // @TODO: throw error if user tries to add self

        $validatedData = $request->validate([
             'isPublic' => 'required|boolean'
        ]);

        if( $validatedData['isPublic'] === true ){
            $collection->makePublic();
        } else {
            $collection->makePrivate();
        }

        return response()->json([], 204);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Collection  $collection
     * @return \Illuminate\Http\Response
     */
    public function destroy(Collection $collection)
    {
        $this->authorize('delete', $collection);

        $collection->delete();

        return redirect()->route('home')->with('status', "Collection deleted");
    }
}

resources/views/layouts/collections/show.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-12">
            <h1>{{ $collection->title }}</h1>
            <p>{{ $collection->description }}</p>
        </div>
    </div>

    <collection-component :initial-user-webpages="{{ $collectionUserWebpages }}" :collection-id="{{ $collection->id }}" inline-template>
        <div class="row">
            <div class="col-12 col-md-8">
                <div v-for="userWebpage in userWebpages" class="row-mb-4">
                    <div class="col-12">
                        {{-- @TODO: remove the 'remove' link in webpage-listitem for non-authorized users --}}
                        <webpage-listitem-component :user-webpage="userWebpage" :button-text="'Remove'"  @destroy="remove" class="mb-3"></webpage-listitem-component>
                    </div>
                </div>
            </div>
            <div class="col-12 col-md-4">
                @can('update', $collection)
                    <webpage-select-form-component :pages-not-in-collection="{{ $userWebpagesNotInCollection }}" @update="updateCollectionPages"></webpage-select-form-component>
                @endcan
                @can('delete', $collection)
                    <br>
                    <form action="{{ route('collection.destroy', ['collection' => $collection]) }}" method="POST">
                        @method('DELETE')
                        @csrf
                        <button class="btn btn-danger">Delete this collection</button>
                    </form>
                @endcan
                @can('authorize-user', $collection)
                    <br>
                    <button class="btn btn-secondary" type="button" data-toggle="modal" data-target="#permissionsModal">Manage Permissions</button>

                    <permissions-modal-component :collection-id="{{ $collection->id }}" :available-roles="{{ $availableRoles }}" :initial-collection-users="{{ $collectionUsers }}" :is-collection-public="{{ json_encode($collection->is_public) }}"></permissions-modal-component>
                @endcan
            </div>
        </div>
    </collection-component>
</div>
@endsection